/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequestDto"];
                    "text/json": components["schemas"]["LoginRequestDto"];
                    "application/*+json": components["schemas"]["LoginRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponseDto"];
                        "application/json": components["schemas"]["AuthResponseDto"];
                        "text/json": components["schemas"]["AuthResponseDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponseDto"];
                        "application/json": components["schemas"]["AuthResponseDto"];
                        "text/json": components["schemas"]["AuthResponseDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateRoomResponseDto"];
                        "application/json": components["schemas"]["CreateRoomResponseDto"];
                        "text/json": components["schemas"]["CreateRoomResponseDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    prompt?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ChatHistoryResponseDto"];
                        "application/json": components["schemas"]["ChatHistoryResponseDto"];
                        "text/json": components["schemas"]["ChatHistoryResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendMessageRequestDto"];
                    "text/json": components["schemas"]["SendMessageRequestDto"];
                    "application/*+json": components["schemas"]["SendMessageRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SendMessageResponseDto"];
                        "application/json": components["schemas"]["SendMessageResponseDto"];
                        "text/json": components["schemas"]["SendMessageResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/{roomId}/result/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: string;
                    messageId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageResponseDto"];
                        "application/json": components["schemas"]["MessageResponseDto"];
                        "text/json": components["schemas"]["MessageResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    excludeEnrolled?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseResponseDto"][];
                        "application/json": components["schemas"]["CourseResponseDto"][];
                        "text/json": components["schemas"]["CourseResponseDto"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCourseDto"];
                    "text/json": components["schemas"]["CreateCourseDto"];
                    "application/*+json": components["schemas"]["CreateCourseDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/simple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SimpleCourseDto"][];
                        "application/json": components["schemas"]["SimpleCourseDto"][];
                        "text/json": components["schemas"]["SimpleCourseDto"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseResponseDto"];
                        "application/json": components["schemas"]["CourseResponseDto"];
                        "text/json": components["schemas"]["CourseResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/create/parsePDF": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    aiProvider?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PdfParseResponseDto"];
                        "application/json": components["schemas"]["PdfParseResponseDto"];
                        "text/json": components["schemas"]["PdfParseResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCourseVersionDto"];
                    "text/json": components["schemas"]["CreateCourseVersionDto"];
                    "application/*+json": components["schemas"]["CreateCourseVersionDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentFactsResponseDto"];
                        "application/json": components["schemas"]["CurrentFactsResponseDto"];
                        "text/json": components["schemas"]["CurrentFactsResponseDto"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facts/codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CodeResponseDto"][];
                        "application/json": components["schemas"]["CodeResponseDto"][];
                        "text/json": components["schemas"]["CodeResponseDto"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facts/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseGroupResponseDto"][];
                        "application/json": components["schemas"]["CourseGroupResponseDto"][];
                        "text/json": components["schemas"]["CourseGroupResponseDto"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facts/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DepartmentResponseDto"][];
                        "application/json": components["schemas"]["DepartmentResponseDto"][];
                        "text/json": components["schemas"]["DepartmentResponseDto"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserCourseDto"][];
                        "application/json": components["schemas"]["UserCourseDto"][];
                        "text/json": components["schemas"]["UserCourseDto"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateStudentCourseDto"][];
                    "text/json": components["schemas"]["CreateStudentCourseDto"][];
                    "application/*+json": components["schemas"]["CreateStudentCourseDto"][];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": unknown;
                        "application/json": unknown;
                        "text/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CategoryCompletionStatus"][];
                        "application/json": components["schemas"]["CategoryCompletionStatus"][];
                        "text/json": components["schemas"]["CategoryCompletionStatus"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/academic-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AcademicProgressDto"];
                        "application/json": components["schemas"]["AcademicProgressDto"];
                        "text/json": components["schemas"]["AcademicProgressDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/programme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserProgrammeDetailDto"];
                        "application/json": components["schemas"]["UserProgrammeDetailDto"];
                        "text/json": components["schemas"]["UserProgrammeDetailDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/category-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CategoryGroupResponseDto"][];
                        "application/json": components["schemas"]["CategoryGroupResponseDto"][];
                        "text/json": components["schemas"]["CategoryGroupResponseDto"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timetable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    year?: number | string;
                    termId?: number | string;
                    courseGroupId?: number | string;
                    categoryGroupId?: number | string;
                    excludeCompletedCourses?: boolean;
                    includeFailedRequirementCourses?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TimetableResponseDto"];
                        "application/json": components["schemas"]["TimetableResponseDto"];
                        "text/json": components["schemas"]["TimetableResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TimetableGenerationRequestDto"];
                    "text/json": components["schemas"]["TimetableGenerationRequestDto"];
                    "application/*+json": components["schemas"]["TimetableGenerationRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TimetableSuggestionsResponseDto"];
                        "application/json": components["schemas"]["TimetableSuggestionsResponseDto"];
                        "text/json": components["schemas"]["TimetableSuggestionsResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcademicProgressDto: {
            semesterGpas?: components["schemas"]["SemesterGpaDto"][];
            /** Format: double */
            overallGpa?: number | string;
            /** Format: int32 */
            totalCreditsCompleted?: number | string;
            /** Format: int32 */
            totalCreditsRequired?: number | string;
            programmeName?: null | string;
            /** Format: int32 */
            enrolledCoursesCount?: number | string;
            /** Format: int32 */
            remainingCredits?: number | string;
            /** Format: double */
            completionPercentage?: number | string;
        };
        /** @enum {unknown} */
        AssessmentCategory: "Examination" | "Assignment" | "Project" | "GroupProject" | "SoloProject" | "Participation" | "Presentation" | "Other";
        AssessmentMethod: {
            name: string;
            /** Format: double */
            weighting?: number | string;
            category?: components["schemas"]["AssessmentCategory"];
            description?: string;
        };
        AssessmentResponseDto: {
            /** Format: int32 */
            id?: number | string;
            name?: string;
            /** Format: double */
            weighting?: number | string;
            category?: string;
            description?: string;
        };
        AuthResponseDto: {
            roles: string[];
            name: string;
            id: string;
        };
        CategoryCompletionStatus: {
            /** Format: int32 */
            id?: number | string;
            name?: null | string;
            ruleNode?: null | components["schemas"]["RuleNode"];
            notes?: null | string;
            /** Format: int32 */
            minCredit?: number | string;
            /** Format: int32 */
            priority?: number | string;
            items?: components["schemas"]["ItemCompletionStatus"][];
            isCompleted?: boolean;
            /** Format: int32 */
            usedCredits?: number | string;
            usedCourseIds?: (number | string)[];
        };
        CategoryGroupDetailDto: {
            /** Format: int32 */
            groupId?: number | string;
            groupName?: string;
            groupCourses?: components["schemas"]["GroupCourseDetailDto"][];
        };
        CategoryGroupResponseDto: {
            /** Format: int32 */
            categoryId?: number | string;
            categoryName?: string;
            courseGroups?: components["schemas"]["SimpleCourseGroupDto"][];
        };
        /** @enum {unknown} */
        CategoryType: "Core" | "Core_Elective" | "Elective" | "GE";
        ChatHistoryResponseDto: {
            messages?: components["schemas"]["MessageResponseDto"][];
        };
        CILOs: {
            code: string;
            description?: string;
        };
        CodeResponseDto: {
            /** Format: int32 */
            id?: number | string;
            tag?: string;
            name?: string;
        };
        CompactGap: {
            /** Format: double */
            rewardPoints?: number | string;
            /** Format: double */
            penaltyPoints?: number | string;
            /** Format: double */
            maxGapMinutes?: number | string;
            /** Format: time */
            ignoreGapStartTime?: string;
            /** Format: time */
            ignoreGapEndTime?: string;
        };
        CourseCodeDto: {
            courseCode?: string;
            courseCodeNumber?: string;
        };
        CourseGroupResponseDto: {
            /** Format: int32 */
            id?: number | string;
            name?: string;
        };
        CourseResponseDto: {
            /** Format: int32 */
            id?: number | string;
            name?: string;
            courseNumber?: string;
            /** Format: int32 */
            codeId?: number | string;
            codeTag?: string;
            /** Format: int32 */
            credit?: number | string;
            description?: null | string;
            isActive?: boolean;
            versions?: components["schemas"]["CourseVersionResponseDto"][];
            departments?: string[];
        };
        /** @enum {unknown} */
        CourseSelectionMode: "OneOf" | "AllOf" | null;
        CourseVersionResponseDto: {
            /** Format: int32 */
            id?: number | string;
            description?: string;
            aimAndObjectives?: string;
            courseContent?: string;
            cilOs?: components["schemas"]["CILOs"][];
            tlAs?: components["schemas"]["TLAs"][];
            /** Format: int32 */
            versionNumber?: number | string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int32 */
            fromYear?: number | string;
            fromTerm?: components["schemas"]["TermResponseDto"];
            /** Format: int32 */
            toYear?: null | number | string;
            toTerm?: null | components["schemas"]["TermResponseDto"];
            assessments?: components["schemas"]["AssessmentResponseDto"][];
            mediumOfInstruction?: string[];
            preRequisites?: components["schemas"]["SimpleCourseDto"][];
            antiRequisites?: components["schemas"]["SimpleCourseDto"][];
        };
        CreateAssessmentDto: {
            name: string;
            /** Format: double */
            weighting?: number | string;
            category?: components["schemas"]["AssessmentCategory"];
            description?: string;
        };
        CreateCourseDto: {
            name: string;
            courseNumber: string;
            /** Format: int32 */
            codeId: number | string;
            /** Format: int32 */
            credit?: number | string;
            description?: null | string;
            groupIds?: (number | string)[];
            departmentIds?: (number | string)[];
            isActive?: boolean;
        };
        CreateCourseVersionDto: {
            description?: string;
            aimAndObjectives?: string;
            courseContent?: string;
            cilOs?: components["schemas"]["CILOs"][];
            tlAs?: components["schemas"]["TLAs"][];
            assessments?: components["schemas"]["CreateAssessmentDto"][];
            mediumOfInstructionIds?: (number | string)[];
            preRequisiteCourseVersionIds?: (number | string)[];
            antiRequisiteCourseVersionIds?: (number | string)[];
            /** Format: int32 */
            fromYear: number | string;
            /** Format: int32 */
            fromTermId: number | string;
            /** Format: int32 */
            toYear?: null | number | string;
            /** Format: int32 */
            toTermId?: null | number | string;
        };
        CreateRoomResponseDto: {
            roomId?: string;
        };
        CreateStudentCourseDto: {
            /** Format: int32 */
            courseId?: number | string;
            /** Format: int32 */
            termId?: number | string;
            /** Format: int32 */
            academicYear?: number | string;
            grade?: null | components["schemas"]["Grade"];
            status?: components["schemas"]["StudentCourseStatus"];
            notes?: string;
        };
        CurrentFactsResponseDto: {
            /** Format: int32 */
            currentSemester?: number | string;
            /** Format: int32 */
            currentAcademicYear?: number | string;
            currentTermName?: null | string;
        };
        DepartmentResponseDto: {
            /** Format: int32 */
            id?: number | string;
            name?: string;
        };
        EndTimePreference: {
            /** Format: time */
            preferredEndTime?: string;
            /** Format: double */
            rewardPoints?: number | string;
            /** Format: double */
            penaltyPoints?: number | string;
        };
        /** @enum {unknown} */
        Grade: "A" | "AMinus" | "BPlus" | "B" | "BMinus" | "CPlus" | "C" | "CMinus" | "D" | "E" | "F" | "DT" | "I" | "S" | "U" | "W" | "IP" | "NA" | null;
        GroupCourseDetailDto: {
            /** Format: int32 */
            groupCourseId?: number | string;
            course?: null | components["schemas"]["SimpleGroupCourseDto"];
            code?: null | components["schemas"]["SimpleCodeDto"];
        };
        /** Format: binary */
        IFormFile: string;
        ItemCompletionStatus: {
            /** Format: int32 */
            groupCourseID: number | string;
            /** Format: int32 */
            courseID?: null | number | string;
            /** Format: int32 */
            codeID?: null | number | string;
            isCompleted?: boolean;
            /** Format: int32 */
            creditsUsed?: number | string;
        };
        LoginRequestDto: {
            username: string;
            password: string;
        };
        MessageResponseDto: {
            id?: string;
            role?: components["schemas"]["MessageRole"];
            content?: string;
            status?: components["schemas"]["MessageStatus"];
            /** Format: date-time */
            createdAt?: string;
        };
        MessageRole: number;
        MessageStatus: number;
        ParsedSectionsDto: {
            courseTitle?: string;
            courseCodeNumber?: string;
            courseCode?: string;
            noOfUnits?: string;
            offeringDepartment?: string;
            prerequisites?: components["schemas"]["CourseCodeDto"][];
            mediumOfInstruction?: string;
            aimsObjectives?: string;
            courseContent?: string;
            cilosRaw?: string;
            cilOs?: components["schemas"]["CILOs"][];
            tlasRaw?: string;
            tlAs?: components["schemas"]["TLAs"][];
            assessmentMethodsRaw?: string;
            assessmentMethods?: components["schemas"]["AssessmentMethod"][];
        };
        PdfParseResponseDto: {
            message?: string;
            filename?: string;
            /** Format: int64 */
            size?: number | string;
            /** Format: int32 */
            pages?: number | string;
            extractedText?: string;
            parsedSections?: components["schemas"]["ParsedSectionsDto"];
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        ProgrammeCategoryDetailDto: {
            /** Format: int32 */
            categoryId?: number | string;
            name?: string;
            type?: components["schemas"]["CategoryType"];
            notes?: string;
            /** Format: int32 */
            minCredit?: number | string;
            /** Format: int32 */
            priority?: number | string;
            rulesJson?: null | string;
            groups?: components["schemas"]["CategoryGroupDetailDto"][];
        };
        RuleNode: components["schemas"]["RuleNodeGroupRuleNode"] | components["schemas"]["RuleNodeRuleRuleNode"] | components["schemas"]["RuleNodeFreeElectiveRuleNode"];
        RuleNodeFreeElectiveRuleNode: {
            /** @enum {string} */
            type?: "free_elective";
            /** Format: int32 */
            minCredits?: null | number | string;
            /** Format: int32 */
            groupID: number | string;
        };
        RuleNodeGroupRuleNode: {
            /** @enum {string} */
            type?: "group";
            /** Format: int32 */
            groupID: number | string;
            courseSelectionMode?: null | components["schemas"]["CourseSelectionMode"];
        };
        RuleNodeRuleRuleNode: {
            /** @enum {string} */
            type?: "rule";
            operator?: null | components["schemas"]["RuleOperator"];
            children?: null | components["schemas"]["RuleNode"][];
        };
        /** @enum {unknown} */
        RuleOperator: "And" | "Any" | null;
        SemesterGpaDto: {
            /** Format: int32 */
            year?: number | string;
            /** Format: int32 */
            semester?: number | string;
            /** Format: double */
            gpa?: number | string;
            /** Format: int32 */
            creditsCompleted?: number | string;
            termName?: string;
        };
        SendMessageRequestDto: {
            message: string;
        };
        SendMessageResponseDto: {
            generatedId?: string;
        };
        SimpleCodeDto: {
            /** Format: int32 */
            codeId?: number | string;
            name?: string;
            tag?: string;
        };
        SimpleCourseDto: {
            /** Format: int32 */
            id?: number | string;
            name?: string;
            courseNumber?: string;
            /** Format: int32 */
            codeId?: number | string;
            codeTag?: string;
            mostRecentVersion?: null | components["schemas"]["CourseVersionResponseDto"];
        };
        SimpleCourseGroupDto: {
            /** Format: int32 */
            groupId?: number | string;
            groupName?: string;
        };
        SimpleGroupCourseDto: {
            /** Format: int32 */
            courseId?: number | string;
            name?: string;
            courseNumber?: string;
            /** Format: int32 */
            credit?: number | string;
            codeTag?: string;
            isActive?: boolean;
            description?: null | string;
        };
        StartTimePreference: {
            /** Format: time */
            preferredStartTime?: string;
            /** Format: double */
            rewardPoints?: number | string;
            /** Format: double */
            penaltyPoints?: number | string;
        };
        /** @enum {unknown} */
        StudentCourseStatus: "Enrolled" | "Completed" | "Dropped" | "Planned" | "Withdrawn" | "Failed" | "Exemption";
        TermResponseDto: {
            /** Format: int32 */
            id?: number | string;
            name?: string;
        };
        TimeTableAssessmentScoring: {
            category?: components["schemas"]["AssessmentCategory"];
            /** Format: double */
            rewardPoints?: number | string;
            /** Format: double */
            penaltyPoints?: number | string;
        };
        TimetableAssessmentShape: {
            assessmentCategoryScores?: components["schemas"]["TimeTableAssessmentScoring"][];
        };
        TimetableDailyLoadScore: {
            /** Format: double */
            rewardPoints?: number | string;
            /** Format: double */
            penaltyPoints?: number | string;
            /** Format: double */
            idealActiveDays?: number | string;
        };
        TimetableEntryDto: {
            /** Format: int32 */
            courseId?: number | string;
            courseName?: string;
            courseCode?: string;
            codeTag?: string;
            courseNumber?: string;
            /** Format: int32 */
            credit?: number | string;
            /** Format: int32 */
            versionId?: number | string;
            /** Format: int32 */
            versionNumber?: number | string;
            sections?: components["schemas"]["TimetableSectionDto"][];
        };
        TimetableFilterDto: {
            /** Format: time */
            earliestStart?: null | string;
            /** Format: time */
            latestEnd?: null | string;
            noClassTime?: components["schemas"]["TimetableNoClassTimeDto"][];
        };
        TimetableGapCompactnessShape: {
            shortGap: components["schemas"]["CompactGap"];
        };
        TimetableGenerationRequestDto: {
            scoring: components["schemas"]["TimetableScoring"];
            filter?: components["schemas"]["TimetableFilterDto"];
        };
        TimetableMeetingDto: {
            /** Format: int32 */
            id?: number | string;
            meetingType?: string;
            /** Format: int32 */
            day?: number | string;
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
        };
        TimetableNoClassTimeDto: {
            /** Format: int32 */
            day?: number | string;
            /** Format: time */
            start?: string;
            /** Format: time */
            end?: string;
        };
        TimetablePreferenceShape: {
            startTimePreference: components["schemas"]["StartTimePreference"];
            endTimePreference: components["schemas"]["EndTimePreference"];
        };
        TimetableResponseDto: {
            /** Format: int32 */
            year?: number | string;
            term?: string;
            entries?: components["schemas"]["TimetableEntryDto"][];
        };
        TimetableScoring: {
            /** Format: int32 */
            baseScore?: number | string;
            groupWeights: components["schemas"]["TimetableScoringGroupWeight"];
            scheduleShape: components["schemas"]["TimetableScoringScheduleShape"];
            preferenceShape: components["schemas"]["TimetablePreferenceShape"];
            gapCompactnessShape: components["schemas"]["TimetableGapCompactnessShape"];
            assessmentShape: components["schemas"]["TimetableAssessmentShape"];
        };
        TimetableScoringFreeDayScore: {
            /** Format: double */
            rewardPoints?: number | string;
            /** Format: double */
            penaltyPoints?: number | string;
        };
        TimetableScoringGroupWeight: {
            /** Format: double */
            schedule?: number | string;
            /** Format: double */
            timePreference?: number | string;
            /** Format: double */
            gap?: number | string;
            /** Format: double */
            assessments?: number | string;
        };
        TimetableScoringLongDayScore: {
            /** Format: double */
            rewardPoints?: number | string;
            /** Format: double */
            penaltyPoints?: number | string;
            /** Format: double */
            maxMinutesPerDay?: number | string;
        };
        TimetableScoringScheduleShape: {
            freeDayScore: components["schemas"]["TimetableScoringFreeDayScore"];
            singleClassDayScore: components["schemas"]["TimetableScoringSingleClassDayScore"];
            longDayScore: components["schemas"]["TimetableScoringLongDayScore"];
            dailyLoadScore: components["schemas"]["TimetableDailyLoadScore"];
        };
        TimetableScoringSingleClassDayScore: {
            /** Format: double */
            rewardPoints?: number | string;
            /** Format: double */
            penaltyPoints?: number | string;
        };
        TimetableSectionDto: {
            /** Format: int32 */
            sectionId?: number | string;
            /** Format: int32 */
            sectionNumber?: number | string;
            meetings?: components["schemas"]["TimetableMeetingDto"][];
        };
        TimetableSuggestionLayoutDto: {
            sections?: components["schemas"]["TimetableSectionDto"][];
            /** Format: double */
            finalScore?: number | string;
            scoreReasons?: string[];
        };
        TimetableSuggestionsResponseDto: {
            layouts?: components["schemas"]["TimetableSuggestionLayoutDto"][];
            errors?: string[];
        };
        TLAs: {
            code: string[];
            description?: string;
        };
        UserCourseDto: {
            /** Format: int32 */
            courseId?: number | string;
            courseName?: string;
            courseNumber?: string;
            /** Format: int32 */
            codeId?: number | string;
            codeTag?: string;
            /** Format: int32 */
            credit?: number | string;
            status?: components["schemas"]["StudentCourseStatus"];
            grade?: null | components["schemas"]["Grade"];
            term?: string;
            /** Format: int32 */
            termNumber?: number | string;
            /** Format: int32 */
            academicYear?: number | string;
            notes?: string;
        };
        UserProgrammeDetailDto: {
            /** Format: int32 */
            programmeVersionId?: number | string;
            /** Format: int32 */
            programmeId?: number | string;
            programmeName?: string;
            programmeDescription?: string;
            /** Format: int32 */
            versionNumber?: number | string;
            /** Format: int32 */
            startYear?: number | string;
            /** Format: int32 */
            endYear?: null | number | string;
            isActive?: boolean;
            /** Format: int32 */
            totalCredits?: number | string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastEditedAt?: string;
            categories?: components["schemas"]["ProgrammeCategoryDetailDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
