// <auto-generated />
using System;
using Backend.Data;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126061040_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MinCredit")
                        .HasColumnType("integer")
                        .HasColumnName("min_credit");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<RuleNode>("Rules")
                        .HasColumnType("jsonb")
                        .HasColumnName("rules");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Backend.Models.CategoryGroup", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.HasKey("CategoryId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("category_groups");
                });

            modelBuilder.Entity("Backend.Models.Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.HasKey("Id");

                    b.ToTable("codes");
                });

            modelBuilder.Entity("Backend.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CodeId")
                        .HasColumnType("integer")
                        .HasColumnName("code_id");

                    b.Property<string>("CourseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_number");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("Backend.Models.CourseAntiReq", b =>
                {
                    b.Property<int>("CourseVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("course_version_id");

                    b.Property<int>("ExcludedCourseVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("excluded_course_version_id");

                    b.HasKey("CourseVersionId", "ExcludedCourseVersionId");

                    b.HasIndex("ExcludedCourseVersionId");

                    b.ToTable("course_anti_reqs");
                });

            modelBuilder.Entity("Backend.Models.CourseDepartment", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.HasKey("CourseId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("course_departments");
                });

            modelBuilder.Entity("Backend.Models.CourseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("course_groups");
                });

            modelBuilder.Entity("Backend.Models.CourseMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("day");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("MeetingType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meeting_type");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("course_meetings");
                });

            modelBuilder.Entity("Backend.Models.CoursePreReq", b =>
                {
                    b.Property<int>("CourseVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("course_version_id");

                    b.Property<int>("RequiredCourseVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("required_course_version_id");

                    b.HasKey("CourseVersionId", "RequiredCourseVersionId");

                    b.HasIndex("RequiredCourseVersionId");

                    b.ToTable("course_pre_reqs");
                });

            modelBuilder.Entity("Backend.Models.CourseSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("course_version_id");

                    b.Property<int>("TermId")
                        .HasColumnType("integer")
                        .HasColumnName("term_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CourseVersionId");

                    b.HasIndex("TermId");

                    b.ToTable("course_sections");
                });

            modelBuilder.Entity("Backend.Models.CourseVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("Credit")
                        .HasColumnType("integer")
                        .HasColumnName("credit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("course_versions");
                });

            modelBuilder.Entity("Backend.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("Backend.Models.GroupCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CodeId")
                        .HasColumnType("integer")
                        .HasColumnName("code_id");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("CourseId");

                    b.HasIndex("GroupId");

                    b.ToTable("group_courses");
                });

            modelBuilder.Entity("Backend.Models.Programme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("programmes");
                });

            modelBuilder.Entity("Backend.Models.ProgrammeCategory", b =>
                {
                    b.Property<int>("ProgrammeVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("programme_version_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.HasKey("ProgrammeVersionId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("programme_categories");
                });

            modelBuilder.Entity("Backend.Models.ProgrammeVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastEditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_at");

                    b.Property<int>("ProgrammeId")
                        .HasColumnType("integer")
                        .HasColumnName("programme_id");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("programme_versions");
                });

            modelBuilder.Entity("Backend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Backend.Models.StudentProgramme", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<int>("ProgrammeVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("programme_version_id");

                    b.HasKey("StudentId", "ProgrammeVersionId");

                    b.HasIndex("ProgrammeVersionId");

                    b.ToTable("student_programmes");
                });

            modelBuilder.Entity("Backend.Models.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("terms");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Backend.Models.CategoryGroup", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("CategoryGroups")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.CourseGroup", "Group")
                        .WithMany("CategoryGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Backend.Models.Course", b =>
                {
                    b.HasOne("Backend.Models.Code", "Code")
                        .WithMany("Courses")
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Code");
                });

            modelBuilder.Entity("Backend.Models.CourseAntiReq", b =>
                {
                    b.HasOne("Backend.Models.CourseVersion", "CourseVersion")
                        .WithMany("AntiRequisites")
                        .HasForeignKey("CourseVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.CourseVersion", "ExcludedCourseVersion")
                        .WithMany("AntiRequisiteFor")
                        .HasForeignKey("ExcludedCourseVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseVersion");

                    b.Navigation("ExcludedCourseVersion");
                });

            modelBuilder.Entity("Backend.Models.CourseDepartment", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("CourseDepartments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Department", "Department")
                        .WithMany("CourseDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Backend.Models.CourseMeeting", b =>
                {
                    b.HasOne("Backend.Models.CourseSection", "CourseSection")
                        .WithMany("CourseMeetings")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSection");
                });

            modelBuilder.Entity("Backend.Models.CoursePreReq", b =>
                {
                    b.HasOne("Backend.Models.CourseVersion", "CourseVersion")
                        .WithMany("Prerequisites")
                        .HasForeignKey("CourseVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.CourseVersion", "RequiredCourseVersion")
                        .WithMany("PrerequisiteFor")
                        .HasForeignKey("RequiredCourseVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseVersion");

                    b.Navigation("RequiredCourseVersion");
                });

            modelBuilder.Entity("Backend.Models.CourseSection", b =>
                {
                    b.HasOne("Backend.Models.CourseVersion", "CourseVersion")
                        .WithMany("CourseSections")
                        .HasForeignKey("CourseVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Term", "Term")
                        .WithMany("CourseSections")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseVersion");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Backend.Models.CourseVersion", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("CourseVersions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Backend.Models.GroupCourse", b =>
                {
                    b.HasOne("Backend.Models.Code", "Code")
                        .WithMany("GroupCourses")
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("GroupCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Models.CourseGroup", "Group")
                        .WithMany("GroupCourses")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Code");

                    b.Navigation("Course");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Backend.Models.ProgrammeCategory", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("ProgrammeCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ProgrammeVersion", "ProgrammeVersion")
                        .WithMany("ProgrammeCategories")
                        .HasForeignKey("ProgrammeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ProgrammeVersion");
                });

            modelBuilder.Entity("Backend.Models.ProgrammeVersion", b =>
                {
                    b.HasOne("Backend.Models.Programme", "Programme")
                        .WithMany("ProgrammeVersions")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("Backend.Models.StudentProgramme", b =>
                {
                    b.HasOne("Backend.Models.ProgrammeVersion", "ProgrammeVersion")
                        .WithMany("StudentProgrammes")
                        .HasForeignKey("ProgrammeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("StudentProgrammes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammeVersion");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.HasOne("Backend.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("CategoryGroups");

                    b.Navigation("ProgrammeCategories");
                });

            modelBuilder.Entity("Backend.Models.Code", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("GroupCourses");
                });

            modelBuilder.Entity("Backend.Models.Course", b =>
                {
                    b.Navigation("CourseDepartments");

                    b.Navigation("CourseVersions");

                    b.Navigation("GroupCourses");
                });

            modelBuilder.Entity("Backend.Models.CourseGroup", b =>
                {
                    b.Navigation("CategoryGroups");

                    b.Navigation("GroupCourses");
                });

            modelBuilder.Entity("Backend.Models.CourseSection", b =>
                {
                    b.Navigation("CourseMeetings");
                });

            modelBuilder.Entity("Backend.Models.CourseVersion", b =>
                {
                    b.Navigation("AntiRequisiteFor");

                    b.Navigation("AntiRequisites");

                    b.Navigation("CourseSections");

                    b.Navigation("PrerequisiteFor");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("Backend.Models.Department", b =>
                {
                    b.Navigation("CourseDepartments");
                });

            modelBuilder.Entity("Backend.Models.Programme", b =>
                {
                    b.Navigation("ProgrammeVersions");
                });

            modelBuilder.Entity("Backend.Models.ProgrammeVersion", b =>
                {
                    b.Navigation("ProgrammeCategories");

                    b.Navigation("StudentProgrammes");
                });

            modelBuilder.Entity("Backend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend.Models.Term", b =>
                {
                    b.Navigation("CourseSections");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("StudentProgrammes");
                });
#pragma warning restore 612, 618
        }
    }
}
