// <auto-generated />
using System;
using System.Collections.Generic;
using Backend.Data;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208095723_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MinCredit")
                        .HasColumnType("integer")
                        .HasColumnName("min_credit");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<RuleNode>("Rules")
                        .HasColumnType("jsonb")
                        .HasColumnName("rules");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Backend.Models.CategoryGroup", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.HasKey("CategoryId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("category_groups");
                });

            modelBuilder.Entity("Backend.Models.Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.HasKey("Id");

                    b.ToTable("codes");
                });

            modelBuilder.Entity("Backend.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CodeId")
                        .HasColumnType("integer")
                        .HasColumnName("code_id");

                    b.Property<string>("CourseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_number");

                    b.Property<int>("Credit")
                        .HasColumnType("integer")
                        .HasColumnName("credit");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("Backend.Models.CourseAntiReq", b =>
                {
                    b.Property<int>("CourseVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("course_version_id");

                    b.Property<int>("ExcludedCourseVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("excluded_course_version_id");

                    b.HasKey("CourseVersionId", "ExcludedCourseVersionId");

                    b.HasIndex("ExcludedCourseVersionId");

                    b.ToTable("course_anti_reqs");
                });

            modelBuilder.Entity("Backend.Models.CourseAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<int>("CourseVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("course_version_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Weighting")
                        .HasColumnType("numeric")
                        .HasColumnName("weighting");

                    b.HasKey("Id");

                    b.HasIndex("CourseVersionId");

                    b.ToTable("course_assessments");
                });

            modelBuilder.Entity("Backend.Models.CourseDepartment", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.HasKey("CourseId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("course_departments");
                });

            modelBuilder.Entity("Backend.Models.CourseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("course_groups");
                });

            modelBuilder.Entity("Backend.Models.CourseMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("day");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("MeetingType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meeting_type");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("course_meetings");
                });

            modelBuilder.Entity("Backend.Models.CoursePreReq", b =>
                {
                    b.Property<int>("CourseVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("course_version_id");

                    b.Property<int>("RequiredCourseVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("required_course_version_id");

                    b.HasKey("CourseVersionId", "RequiredCourseVersionId");

                    b.HasIndex("RequiredCourseVersionId");

                    b.ToTable("course_pre_reqs");
                });

            modelBuilder.Entity("Backend.Models.CourseSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("course_version_id");

                    b.Property<int>("SectionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("section_number");

                    b.Property<int>("TermId")
                        .HasColumnType("integer")
                        .HasColumnName("term_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CourseVersionId");

                    b.HasIndex("TermId");

                    b.ToTable("course_sections");
                });

            modelBuilder.Entity("Backend.Models.CourseVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AimAndObjectives")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aim_and_objectives");

                    b.Property<string>("CourseContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_content");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Credit")
                        .HasColumnType("integer")
                        .HasColumnName("credit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FromTermId")
                        .HasColumnType("integer")
                        .HasColumnName("from_term_id");

                    b.Property<int>("FromYear")
                        .HasColumnType("integer")
                        .HasColumnName("from_year");

                    b.Property<int?>("ToTermId")
                        .HasColumnType("integer")
                        .HasColumnName("to_term_id");

                    b.Property<int?>("ToYear")
                        .HasColumnType("integer")
                        .HasColumnName("to_year");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "CILOs", "Backend.Models.CourseVersion.CILOs#CILOs", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired();

                            b1.Property<string>("code")
                                .IsRequired();

                            b1.ToJson("CILOs");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "TLAs", "Backend.Models.CourseVersion.TLAs#TLAs", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Description")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("code")
                                .IsRequired();

                            b1.ToJson("TLAs");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("FromTermId");

                    b.HasIndex("ToTermId");

                    b.ToTable("course_versions");
                });

            modelBuilder.Entity("Backend.Models.CourseVersionMedium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("course_version_id");

                    b.Property<int>("MediumOfInstructionId")
                        .HasColumnType("integer")
                        .HasColumnName("medium_of_instruction_id");

                    b.HasKey("Id");

                    b.HasIndex("CourseVersionId");

                    b.HasIndex("MediumOfInstructionId");

                    b.ToTable("course_version_mediums");
                });

            modelBuilder.Entity("Backend.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("Backend.Models.GroupCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CodeId")
                        .HasColumnType("integer")
                        .HasColumnName("code_id");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("CourseId");

                    b.HasIndex("GroupId");

                    b.ToTable("group_courses");
                });

            modelBuilder.Entity("Backend.Models.MediumOfInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("medium_of_instructions");
                });

            modelBuilder.Entity("Backend.Models.Programme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("programmes");
                });

            modelBuilder.Entity("Backend.Models.ProgrammeCategory", b =>
                {
                    b.Property<int>("ProgrammeVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("programme_version_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.HasKey("ProgrammeVersionId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("programme_categories");
                });

            modelBuilder.Entity("Backend.Models.ProgrammeVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnName("end_year");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastEditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_edited_at");

                    b.Property<int>("ProgrammeId")
                        .HasColumnType("integer")
                        .HasColumnName("programme_id");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("programme_versions");
                });

            modelBuilder.Entity("Backend.Models.StudentCourse", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year");

                    b.Property<string>("Grade")
                        .HasColumnType("text")
                        .HasColumnName("grade");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("TermId")
                        .HasColumnType("integer")
                        .HasColumnName("term_id");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TermId");

                    b.ToTable("student_courses");
                });

            modelBuilder.Entity("Backend.Models.StudentProgramme", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<int>("ProgrammeVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("programme_version_id");

                    b.HasKey("StudentId", "ProgrammeVersionId");

                    b.HasIndex("ProgrammeVersionId");

                    b.ToTable("student_programmes");
                });

            modelBuilder.Entity("Backend.Models.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("terms");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "08fb9bd6-eeda-4063-9be8-ffadd4a09a39",
                            ConcurrencyStamp = "4e544a59-030f-4446-86ef-8ded2fa0aebf",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "f54b9699-348d-45b3-8fbb-83d5591b2aef",
                            ConcurrencyStamp = "5bf897a4-3ddd-41f3-8f8a-5526f3b008dd",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Backend.Models.CategoryGroup", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("CategoryGroups")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.CourseGroup", "Group")
                        .WithMany("CategoryGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Backend.Models.Course", b =>
                {
                    b.HasOne("Backend.Models.Code", "Code")
                        .WithMany("Courses")
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Code");
                });

            modelBuilder.Entity("Backend.Models.CourseAntiReq", b =>
                {
                    b.HasOne("Backend.Models.CourseVersion", "CourseVersion")
                        .WithMany("AntiRequisites")
                        .HasForeignKey("CourseVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.CourseVersion", "ExcludedCourseVersion")
                        .WithMany("AntiRequisiteFor")
                        .HasForeignKey("ExcludedCourseVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseVersion");

                    b.Navigation("ExcludedCourseVersion");
                });

            modelBuilder.Entity("Backend.Models.CourseAssessment", b =>
                {
                    b.HasOne("Backend.Models.CourseVersion", "CourseVersion")
                        .WithMany("Assessments")
                        .HasForeignKey("CourseVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseVersion");
                });

            modelBuilder.Entity("Backend.Models.CourseDepartment", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("CourseDepartments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Department", "Department")
                        .WithMany("CourseDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Backend.Models.CourseMeeting", b =>
                {
                    b.HasOne("Backend.Models.CourseSection", "CourseSection")
                        .WithMany("CourseMeetings")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSection");
                });

            modelBuilder.Entity("Backend.Models.CoursePreReq", b =>
                {
                    b.HasOne("Backend.Models.CourseVersion", "CourseVersion")
                        .WithMany("Prerequisites")
                        .HasForeignKey("CourseVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.CourseVersion", "RequiredCourseVersion")
                        .WithMany("PrerequisiteFor")
                        .HasForeignKey("RequiredCourseVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseVersion");

                    b.Navigation("RequiredCourseVersion");
                });

            modelBuilder.Entity("Backend.Models.CourseSection", b =>
                {
                    b.HasOne("Backend.Models.CourseVersion", "CourseVersion")
                        .WithMany("CourseSections")
                        .HasForeignKey("CourseVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Term", "Term")
                        .WithMany("CourseSections")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseVersion");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Backend.Models.CourseVersion", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("CourseVersions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Term", "FromTerm")
                        .WithMany()
                        .HasForeignKey("FromTermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.Term", "ToTerm")
                        .WithMany()
                        .HasForeignKey("ToTermId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("FromTerm");

                    b.Navigation("ToTerm");
                });

            modelBuilder.Entity("Backend.Models.CourseVersionMedium", b =>
                {
                    b.HasOne("Backend.Models.CourseVersion", "CourseVersion")
                        .WithMany("CourseVersionMediums")
                        .HasForeignKey("CourseVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.MediumOfInstruction", "MediumOfInstruction")
                        .WithMany("CourseVersionMediums")
                        .HasForeignKey("MediumOfInstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseVersion");

                    b.Navigation("MediumOfInstruction");
                });

            modelBuilder.Entity("Backend.Models.GroupCourse", b =>
                {
                    b.HasOne("Backend.Models.Code", "Code")
                        .WithMany("GroupCourses")
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("GroupCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Models.CourseGroup", "Group")
                        .WithMany("GroupCourses")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Code");

                    b.Navigation("Course");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Backend.Models.ProgrammeCategory", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("ProgrammeCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.ProgrammeVersion", "ProgrammeVersion")
                        .WithMany("ProgrammeCategories")
                        .HasForeignKey("ProgrammeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ProgrammeVersion");
                });

            modelBuilder.Entity("Backend.Models.ProgrammeVersion", b =>
                {
                    b.HasOne("Backend.Models.Programme", "Programme")
                        .WithMany("ProgrammeVersions")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("Backend.Models.StudentCourse", b =>
                {
                    b.HasOne("Backend.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Term", "Term")
                        .WithMany("StudentCourses")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Backend.Models.StudentProgramme", b =>
                {
                    b.HasOne("Backend.Models.ProgrammeVersion", "ProgrammeVersion")
                        .WithMany("StudentProgrammes")
                        .HasForeignKey("ProgrammeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("StudentProgrammes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammeVersion");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("CategoryGroups");

                    b.Navigation("ProgrammeCategories");
                });

            modelBuilder.Entity("Backend.Models.Code", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("GroupCourses");
                });

            modelBuilder.Entity("Backend.Models.Course", b =>
                {
                    b.Navigation("CourseDepartments");

                    b.Navigation("CourseVersions");

                    b.Navigation("GroupCourses");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("Backend.Models.CourseGroup", b =>
                {
                    b.Navigation("CategoryGroups");

                    b.Navigation("GroupCourses");
                });

            modelBuilder.Entity("Backend.Models.CourseSection", b =>
                {
                    b.Navigation("CourseMeetings");
                });

            modelBuilder.Entity("Backend.Models.CourseVersion", b =>
                {
                    b.Navigation("AntiRequisiteFor");

                    b.Navigation("AntiRequisites");

                    b.Navigation("Assessments");

                    b.Navigation("CourseSections");

                    b.Navigation("CourseVersionMediums");

                    b.Navigation("PrerequisiteFor");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("Backend.Models.Department", b =>
                {
                    b.Navigation("CourseDepartments");
                });

            modelBuilder.Entity("Backend.Models.MediumOfInstruction", b =>
                {
                    b.Navigation("CourseVersionMediums");
                });

            modelBuilder.Entity("Backend.Models.Programme", b =>
                {
                    b.Navigation("ProgrammeVersions");
                });

            modelBuilder.Entity("Backend.Models.ProgrammeVersion", b =>
                {
                    b.Navigation("ProgrammeCategories");

                    b.Navigation("StudentProgrammes");
                });

            modelBuilder.Entity("Backend.Models.Term", b =>
                {
                    b.Navigation("CourseSections");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("StudentCourses");

                    b.Navigation("StudentProgrammes");
                });
#pragma warning restore 612, 618
        }
    }
}
